### GET
http://localhost:3000/cursos

### GET
GET http://localhost:3000/cursos/1

### POST
POST http://localhost:3000/cursos HTTP/1.1
content-type: application/json

{
  "name": "PHP"
}

### PUT
PUT http://localhost:3000/cursos/4 HTTP/1.1
content-type: application/json

{
  "name": "PHP"
}

### Delete
DELETE http://localhost:3000/cursos/4
